export const POST_TYPES = {
  FETCH_POST_PER_USER_STARTED: 'FETCH_POST_PER_USER_STARTED',
  FETCH_POST_PER_USER_SUCCESS: 'FETCH_POST_PER_USER_SUCCESS',
  FETCH_POST_PER_USER_FAILURE: 'FETCH_POST_PER_USER_FAILURE',
  FETCH_POST_BY_ID_STARTED: 'FETCH_POST_BY_ID_STARTED',
  FETCH_POST_BY_ID_SUCCESS: 'FETCH_POST_BY_ID_SUCCESS',
  FETCH_POST_BY_ID_FAILURE: 'FETCH_POST_BY_ID_FAILURE',
};
